### ISSUE TITLE
Ottimizzazione per  il caso in cui non ci siano snapshots

### ISSUE THREAD

**Issue by spoto** [Hotmoka/hotmoka#8]
Marco, questa "ottimizzazione" ti torna?

https://github.com/Hotmoka/hotmoka/blob/511d09e94c992d548d957be3ba9da37de3ae8d93/io-hotmoka-examples/src/main/java/io/hotmoka/examples/tokens/ERC20OZSnapshot.java#L218

**Comment by marcocrosara96** [comment]
Sì, mi torna!

L'ottimizzazione prevede di ridurre la computazione durante l'elaborazione di nuove transazioni nel caso in cui l'id attuale dello snapshot (`_currentSnapshotId`) sia zero. Intuitivamente è corretto ipotizzare che nel caso in cui nessuno snapshot sia stato richiesto (altrimenti l'id sarebbe > 0, i.e. il primo snapshot ha id 1) nessuna modifica debba essere apportata agli Snapshots dei `Contract` o del `totalSupply`. In ogni caso è necessario accertarsi che tale ottimizzazione non alteri in nessun modo il comportamento di ERC20OZSnapshot. Visto `_updateAccountSnapshot` e `_updateTotalSupplySnapshot` sono funzioni che non ritornano nulla e visto che con questa modifica, nel caso in cui `_currentSnapshotId` sia 0, la loro esecuzione termina subito, siamo certi che lo stato del contratto non viene alterato in alcun modo. Per essere sicuri che l'ottimizzazione apportata non abbia modificato il comportamento del contratto bisogna quindi assicurarsi che anche senza l'aggiunta di tale costrutto condizionale, nel caso in cui il `_currentSnapshotId` sia 0, non avvenga alcuna modifica "rilevante" allo stato del contratto tramite queste due funzioni.

Divido quindi la risposta in tre sezioni:
    - Facciamo vedere a parole che anche precedentemente all'introduzione dell'ottimizzazione, lo stato del contratto non viene alterato nel caso in cui `_currentSnapshotId` sia zero
    - Valutiamo pro e contro dell'ottimizzazione proposta
    - Valutiamo un possibile miglioramento ulteriore

### L'ottimizzazione non modifica il comportamento del contratto

Prima dell'ottimizzazione, all'esecuzione della `beforeTokenTransfer` il corpo delle funzioni `_updateAccountSnapshot` e `_updateTotalSupplySnapshot` veniva eseguito interamente:

-  `_updateAccountSnapshot()` ha due istruzioni: 
 

   1.  `_accountBalanceSnapshots.computeIfAbsent(account, Snapshots::new);` -> Questa istruzione modificherebbe lo stato del contratto poiché associa un nuovo Snapshots all'account corrente. Ma non è un problema, infatti ai fini delle funzionalità del contratto se non viene aggiunto alcun valore alla struttura Snapshot, nulla comunque cambia. Avendo inserito l'ottimizzazione posticipiamo anzi questa fase al primo trasferimento che coinvolge l'account in seguito alla richiesta del primo snapshot.

   2. `_updateSnapshot(_accountBalanceSnapshots.get(account), balanceOf(account));` -> Tale funzione chiamata ha come prima istruzione `if (_lastSnapshotId(snapshots.ids).compareTo(_currentSnapshotId) < 0)` e nel caso questa condizione sia falsa vi è il return immediato senza modifiche allo stato del contratto. Ma tale condizione nel caso in cui `_currentSnapshotId == 0` è sempre falsa! Questo avviene perché se `_currentSnapshotId == 0` allora la chiamata `_lastSnapshotId` ritorna il BigInteger 0 (visto infatti nessuno snapshot è stato creato allora `ids.size()` dell'istanza di Snapshots è 0) ma `0.compareTo(0)` è 0; quindi la condizione è sempre falsa.
        
- ` updateTotalSupplySnapshot()` ha un unica istruzione:

   1. `_updateSnapshot(_totalSupplySnapshots, totalSupply());` -> Stesso Ragionamento della chiamata precedente su `_updateAccountSnapshot`.

Quindi abbiamo la certezza che l'ottimizzazione proposta non altera in alcun modo le funzionalità.

### Pro e contro della modifica

**PRO**
- Evito controlli inutili nel caso in cui so già che non è mai stato richiesto alcuno snapshot. Rimuove soprattutto la chiamata "anticipata" al costruttore di `Snapshots` nel caso in cui nessuna istantanea sia stata richiesta.

**CONTRO**
- Dobbiamo considerare però che se un programmatore decide di usare `ERC20OZSnapshot` invece di `ERC20` probabilmente è intenzionato a fare snapshot! Quindi in seguito alla prima istantanea acquisita l'ottimizzazione risulta essere un test inutile che viene fatto in più ad ogni trasfer/transferFrom/mint/burn. Poiché il test sarà sempre vero il corpo delle due funzioni verrà sempre eseguito.
- l'idea originale di `ERC20OZSnapshot` era replicare il più fedelmente possibile ERC20Snapshot di O.Z. senza applicare ottimizzazioni che abbiamo invece apportato all'implementazione nativa. Con questa ottimizzazione andiamo ad alterare l'idea del codice di O.Z.

### Possibile ulteriore miglioramento

Visto l'ottimizzazione prevede di ridurre la computazione durante l'elaborazione di nuove transazioni quando non esistono snapshot, possiamo unificare il controllo spostandolo direttamente sulla `beforeTokenTransfer`. Se non è stato mai richiesto alcuno snapshot ritorno direttamente. 

```
@Override
protected void beforeTokenTransfer(Contract from, Contract to, UnsignedBigInteger amount) {
    super.beforeTokenTransfer(from, to, amount);

    if (_currentSnapshotId.signum() == 0) // <<----------------------------------
        return;

    if (from == null) { // mint
        _updateAccountSnapshot(to);
        _updateTotalSupplySnapshot();
    } else if (to == null) { // burn
        _updateAccountSnapshot(from);
        _updateTotalSupplySnapshot();
    } else { // transfer
        _updateAccountSnapshot(from);
        _updateAccountSnapshot(to);
    }
}
```

Far vedere che questa ottimizzazione non altera il funzionamento del contratto è semplice. Abbiamo già fatto vedere che l'inserimento del controllo non altera le funzionalità in `_updateAccountSnapshot` e `_updateTotalSupplySnapshot` ma queste due funzioni vengono chiamate unicamente nella `beforeTokenTransfer` (distinguendo tra mint/burn e transfer normali) e la `beforeTokenTransfer` non ha altre istruzioni che potrebbero modificare lo stato. In pratica abbiamo anticipato e unificato il controllo, nel caso in cui `_currentSnapshotId.signum() == 0` evitiamo direttamente di chiamare le due funzioni.

**Comment by spoto** [comment]
Ok, preferisco mettere il controllo a monte dentro beforeTokenTransfer(). Anche se ci allontaniamo un minimo da OZ, questo ci permette di mostrare che i costi sono gli stessi della versione nativa se non si fanno snapshot, il che può essere importante per l'articolo.
